name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      etcd:
        image: quay.io/coreos/etcd:v3.5.16
        ports:
          - 2379:2379
        env:
          ETCD_AUTO_COMPACTION_MODE: revision
          ETCD_AUTO_COMPACTION_RETENTION: 1000
          ETCD_QUOTA_BACKEND_BYTES: 4294967296
          ETCD_SNAPSHOT_COUNT: 50000

      minio:
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        entrypoint: ''
        command: server /data --console-address ":9001"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Start Milvus
        run: |
          docker run -d --name milvus \
            --add-host etcd:127.0.0.1 \
            --add-host minio:127.0.0.1 \
            -e ETCD_ENDPOINTS=etcd:2379 \
            -e MINIO_ADDRESS=minio:9000 \
            -e MINIO_ACCESS_KEY=minioadmin \
            -e MINIO_SECRET_KEY=minioadmin \
            -p 19530:19530 \
            -p 9091:9091 \
            milvusdb/milvus:v2.5.4 \
            milvus run standalone

      - name: Wait for Milvus
        run: |
          echo "Waiting for Milvus..."
          for i in {1..60}; do
            curl -f http://localhost:9091/healthz && echo "Milvus ready" && exit 0
            sleep 2
          done
          echo "Milvus did not start in time" && exit 1

      - name: Run tests
        run: pytest
