name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      milvus:
        image: milvusdb/milvus:v2.3.9
        ports:
          - 19530:19530
        options: >-
          --health-cmd "curl -f http://localhost:9091/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Wait for Milvus to be ready
        run: |
          echo "Waiting for Milvus..."
          for i in {1..10}; do
            nc -zv localhost 19530 && echo "Milvus is up!" && break
            sleep 5
          done

      - name: Run tests
        run: pytest
